---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gyu5la0fbzjq/public_html/shop.casaglick.com/

    - /bin/mkdir -p $DEPLOYPATH

    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp productos.html $DEPLOYPATH
    - /bin/cp producto.html $DEPLOYPATH
    - /bin/cp bolsa.html $DEPLOYPATH
    - /bin/cp checkout.html $DEPLOYPATH
    - /bin/cp confirmacion.html $DEPLOYPATH

    - /bin/cp *.js $DEPLOYPATH
    - /bin/cp *.css $DEPLOYPATH

    - /bin/rm -rf ${DEPLOYPATH}/assets
    - /bin/cp -R assets $DEPLOYPATH
