---
deployment:
  tasks:
    - export DEPLOYPATH=/home/gyu5la0fbzjq/public_html/shop.casaglick.com/

    - /bin/mkdir -p $DEPLOYPATH

    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp productos.html $DEPLOYPATH
    - /bin/cp producto.html $DEPLOYPATH
    - /bin/cp bolsa.html $DEPLOYPATH
    - /bin/cp checkout.html $DEPLOYPATH
    - /bin/cp confirmacion.html $DEPLOYPATH
    - if [ -f 404.html ]; then /bin/cp 404.html $DEPLOYPATH; fi

    - /bin/rm -rf ${DEPLOYPATH}/assets
    - /bin/rm -rf ${DEPLOYPATH}/css
    - /bin/rm -rf ${DEPLOYPATH}/js
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH

    - /bin/rm -f ${DEPLOYPATH}/*.js
    - /bin/rm -f ${DEPLOYPATH}/*.css
